language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
    - ~/.npm
before_install:
  - yarn global add gulp
cache:
  directories:
    - "node_modules"
script:
  - yarn run build
deploy:
  provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    branch: master