language: node_js
node_js:
  - "8"
notifications:
  email: false
cache:
  yarn: true
  directories:
    - "node_modules"
    - ~/.npm
before_install:
  - yarn global add gulp
script:
  - yarn run build
  - yarn run generate-features-docs
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run semantic-release