language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
    - yarn global add gulp
cache:
  directories:
    - "node_modules"
script:
    - yarn run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master